FROM linaro/ci-#{ARCH}-tcwg-base-ubuntu:#{DISTRO}

RUN while read line; do \
      if [ x"$(echo "$line" | cut -d: -f 4)" != x"9000" ]; then \
        continue; \
      fi; \
      new-user.sh --passwd "$line"; \
      user=$(echo "$line" | cut -d: -f 1); \
      sudo -i -u $user ccache -p; \
    done </home-data/passwd

#if ARCH_amd64 || ARCH_i386
# Install wine.  On amd64 arch we need to enable i386, otherwise wine
# won't meet dependencies (this is the case at least for trusty and xenial).
RUN \
#if ARCH_amd64 && DISTRO_xenial
 dpkg --add-architecture i386 && \
#endif
 apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
#if DISTRO_xenial
 wine \
#else
 wine-stable \
#endif
 && apt-get clean \
 && rm -rf \
 /var/lib/apt/lists/* \
 /tmp/* \
 /var/tmp/*
#endif
