#if DISTRO_xenial
# if ARCH_amd64
FROM ubuntu:#{DISTRO}
# else
FROM linaro/base-#{ARCH}-ubuntu:#{DISTRO}
# endif
#else
# if ARCH_armhf
FROM arm32v7/ubuntu:#{DISTRO}
# else
FROM ubuntu:#{DISTRO}
# endif
#endif

# Use bash for better string escaping (on Ubuntu, /bin/sh is dash).
SHELL ["/bin/bash", "-c"]

#if DISTRO_xenial
#if ARCH_amd64 || ARCH_i386
RUN (url="http://archive.ubuntu.com/ubuntu/"; \
#else
RUN (url="http://ports.ubuntu.com/ubuntu-ports/"; \
#endif
 ubuntu=#{DISTRO}; \
 for i in $ubuntu $ubuntu-updates $ubuntu-backports $ubuntu-security; do \
   for j in deb deb-src; do \
     echo "$j $url $i main restricted universe multiverse"; \
   done; \
   echo; \
 done) > /etc/apt/sources.list \
#else
# Unminimize Ubuntu Bionic to install contrib files of git (after package
# update, otherwise unminimize's "apt upgrade" might fail).
RUN true \
#endif
 && apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get dist-upgrade -y \
#if !DISTRO_xenial
 && echo y | unminimize \
#endif
#if ARCH_i386
 && dpkg-divert --local --rename --add /sbin/initctl \
 && ln -s /bin/true /sbin/initctl \
#endif
 && DEBIAN_FRONTEND=noninteractive apt-get install -y devscripts \
 && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
 alien \
 autoconf \
 autogen \
 automake \
 bc \
 bind9-host \
 bison \
#if ARCH_amd64 || ARCH_i386
 binutils-aarch64-linux-gnu \
 binutils-arm-linux-gnueabihf \
#endif
 binutils-dev \
 bsd-mailx \
 build-essential \
 byacc \
 ccache \
 ccrypt \
 chrpath \
 clang \
#if !DISTRO_xenial && !DISTRO_bionic
 cmake \
#endif
 curl \
 debhelper \
 dejagnu \
 dh-autoreconf \
 dh-translations \
 distro-info-data \
 emacs \
 fakeroot \
 flex \
 gawk \
 gdb \
 gdbserver \
 git \
 groff \
 less \
 libexpat1-dev \
 libffi-dev \
 libglib2.0-dev \
 libgmp-dev \
 liblzma-dev \
 libmpc-dev \
 libmpfr-dev \
 libncurses5-dev \
 libpixman-1-dev \
 libpython2.7-dev \
 libreadline-dev \
 libssl-dev \
 libtcnative-1 \
 libtool \
 locales \
 lzop \
 make \
#if ARCH_amd64 || ARCH_i386
 mingw-w64 \
#endif
 moreutils \
 net-tools \
 netcat \
 nfs-kernel-server \
 ninja-build \
 ntp \
 openjdk-8-jdk \
 openssh-server \
 pkg-config \
 postfix \
 psmisc \
#if DISTRO_xenial || DISTRO_bionic
 pxz \
 python-dev \
 python-pip \
 python-setuptools \
 python-wheel \
#else
# pxz \
 python2-dev \
# python2-pip \
# python2-setuptools \
# python2-wheel \
#endif
 python3-dev \
 python3-pip \
 python3-setuptools \
 python3-wheel \
 rsync \
 subversion \
 sudo \
 swig \
 tclsh \
 texinfo \
 texlive-fonts-recommended \
 texlive-latex-recommended \
 time \
 unifdef \
 valgrind \
 vim \
 virtualenv \
 wget \
 xz-utils \
 zip \
 zlib1g-dev \
 shellcheck \
# Update tzdata, because some base images have an incorrect file for UTC.
 && DEBIAN_FRONTEND=noninteractive apt-get install --reinstall tzdata \
 && rm -f /etc/ssh/ssh_host_*_key* \
 && apt-get clean \
 && rm -rf \
 /var/lib/apt/lists/* \
 /tmp/* \
 /var/tmp/*

RUN install -D -p -m0755 /usr/share/doc/git/contrib/workdir/git-new-workdir /usr/local/bin/git-new-workdir \
 && sed -i -e 's:^session *required *pam_loginuid.so:# session required pam_loginuid.so:' /etc/pam.d/sshd \
 && mkdir -p /var/run/sshd \
 && sed -i \
 -e "/.*MaxStartups.*/d" \
 -e "/.*MaxSessions.*/d" /etc/ssh/sshd_config \
 && echo "MaxStartups 256" >> /etc/ssh/sshd_config \
 && echo "MaxSessions 256" >> /etc/ssh/sshd_config \
 && locale-gen en_US.UTF-8 && update-locale LANG=en_US.UTF-8 \
#if !DISTRO_xenial && !DISTRO_bionic
 # Add /usr/bin/python link for focal.  We need this for GDB builds.
 && update-alternatives --install /usr/bin/python python /usr/bin/python3 3 \
#endif
 && pip3 install git-review \
 && pip3 install psutil

#if !DISTRO_xenial
# Install jipdate.  It is tricky to make these work
# for Trusty and Xenial, so don't bother.
RUN git clone -b master https://github.com/Linaro/jipdate.git /usr/local/jipdate/ \
 && git -C /usr/local/jipdate/ fetch origin pull/36/head:pull-36 \
 && git -C /usr/local/jipdate/ checkout pull-36 \
 && pip3 install -U -r /usr/local/jipdate/requirements.txt \
 && ln -s /usr/local/jipdate/jipdate.py /usr/local/bin/jipdate.py
#endif

COPY postfix-main.cf.in /etc/postfix/main.cf
COPY postfix-sasl_password.in /etc/postfix/sasl_password

RUN chown root:root /etc/postfix/sasl_password \
 && chmod 600 /etc/postfix/sasl_password

# Add ninja with support for memory-threshold job limitation.
# It's installed with ".bin" extension and containers then
# make wrappers around it in /usr/local/bin/ninja as needed.
RUN git clone -b master https://github.com/maxim-kuvyrkov/ninja.git \
 && cd ninja \
 && ./configure.py --bootstrap && ./ninja all && ./ninja_test \
 && mv ninja /usr/local/bin/ninja.bin \
 && cd .. \
 && rm -rf ninja


#if DISTRO_bionic
# Configure linux tools for benchmarking support.
#
# We symlink linux tools to supportted "hw_tags": tk1_32, tx1_64, tx1_32.
# HW_TAGS represent tested configurations of hardware+kernel+perf that
# work well together.  We create new hw_tag for any variation in hardware,
# kernel, or perf.  This gives us assurance that benchmarking data stored
# under bkp-01.tcwglab:results-<HW_TAG>/ directory has no unexpected variations.
#
# For the initial hw_tags for TK1s and TX1s we can use nice short tk1_32,
# tx1_64, and tx1_32 names, but if we update, say, perf version, we would
# need to add something like tk1_32-lt_5.4 (updating linux-tools to 5.4) or
# tx1_64-k_4.10 (updating kernel to 4.10).
#
# Below linux-tools versions have proven to work well with TK1s' 3.10 and
# TX1s' 4.4 kernels.
RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
# cpufrequtils is used by our benchmarking scripts, but we should update them to
# use cpupower from linux-tools everywhere instead.
 cpufrequtils \
 linux-tools-common \
 linux-tools-4.18.0-13-generic \
 && apt-get clean \
 && rm -rf \
 /var/lib/apt/lists/* \
 /tmp/* \
 /var/tmp/* \
 && ln -s /usr/lib/linux-tools/4.18.0-13-generic /usr/lib/linux-tools/tk1_32 \
 && ln -s /usr/lib/linux-tools/4.18.0-13-generic /usr/lib/linux-tools/tx1_32 \
 && ln -s /usr/lib/linux-tools/4.18.0-13-generic /usr/lib/linux-tools/tx1_64
#endif
#if DISTRO_bionic
# if ARCH_amd64
# Install usb libs and OpenOCD on x86 hosts, used to target bare-metal boards.
RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
 libusb-1.0 \
 libusb-dev \
 && apt-get clean \
 && rm -rf \
 /var/lib/apt/lists/* \
 /tmp/* \
 /var/tmp/*
RUN cd /tmp \
 && git clone --single-branch --depth 1 https://git.code.sf.net/p/openocd/code openocd \
 && cd /tmp/openocd \
 && ./bootstrap \
 && ./configure --enable-stlink \
 && make -j$(nproc --all) \
 && make -j$(nproc --all) install \
 && cd /tmp \
 && rm -rf /tmp/openocd
# endif
#endif

#if DISTRO_xenial || DISTRO_bionic
# Install cmake v3.16 (same as in upcoming Ubuntu Focal images)
RUN cd /tmp \
 && git clone -b v3.16.6 --single-branch --depth 1 https://github.com/Kitware/CMake.git \
 && cd /tmp/CMake \
 && ./bootstrap --parallel=$(nproc --all) \
 && make -j$(nproc --all) \
 && make -j$(nproc --all) install \
 && cd /tmp \
 && rm -rf /tmp/CMake
#endif

COPY home-data/ /home-data/
COPY new-user.sh nvidia-power-cycle.sh nvidia-serial.sh /usr/local/bin/

RUN \
 while read line; do \
   new-user.sh --group $(echo "$line" | cut -d: -f 1,3); \
 done </home-data/group

# Create directories required for X11.  We use X11 in tcwg-x2go images and,
# sometimes, in tcwg-dev images.
# We need to create these before "VOLUME /tmp" directive, since after
# the directive stuff from /tmp won't make it into the image.
RUN mkdir -p /tmp/.X11-unix /tmp/.ICE-unix \
 && chmod 1777 /tmp/.X11-unix /tmp/.ICE-unix

#if ARCH_armhf || ARCH_i386
# For AArch32 images, add a warning if an interactive shell is opened in an
# AArch64 environment.
RUN echo $'if [ "$(uname -m)" == "aarch64" ] || [ "$(uname -m)" == "x86_64" ]; then\n' \
         $'  echo "============================================================================================="\n' \
         $'  echo "WARNING: This is a 32-bit container, but your shell is running in a 64-bit environment."\n' \
         $'  echo "You probably want to run your shell with the \'linux32\' program to get a 32-bit environment."\n' \
         $'  echo "============================================================================================="\n' \
         $'fi\n' \
         >> /etc/bash.bashrc
#endif

# We use ssh multiplexing, which creates sockets in /tmp.  Overlayfs,
# which docker is using, can't host sockets, so we use a scratch mount
# for /tmp.  This requires that we add --rm option to "docker run"
# invocations (e.g., mark "Remove volumes" checkbox in docker plugin) to
# cleanup host directories used for the scratch mounts.
VOLUME /tmp

EXPOSE 22
#if ARCH_amd64 || ARCH_arm64
CMD ["/usr/sbin/sshd", "-D"]
#else
CMD ["linux32", "/usr/sbin/sshd", "-D"]
#endif
