FROM linaro/ci-#{ARCH}-tcwg-base-ubuntu:#{DISTRO}

RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get install -y \
 apt-file \
 git-gui \
 git-svn \
 gnat \
 less \
 mc \
 screen \
 software-properties-common \
 stgit \
 tmux \
 && apt-get clean \
 && rm -rf \
 /var/lib/apt/lists/* \
 /tmp/* \
 /var/tmp/*

RUN apt-file update

COPY run.sh start.sh /

#if ARCH_amd64 || ARCH_arm64
ENTRYPOINT ["/run.sh"]
#else
ENTRYPOINT ["linux32", "/run.sh"]
#endif
CMD ["start.sh"]
