FROM linaro/ci-#{ARCH}-tcwg-base-ubuntu:#{DISTRO}

RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get install -y \
 software-properties-common \
 && apt-get clean \
 && rm -rf \
 /var/lib/apt/lists/* \
 /tmp/* \
 /var/tmp/*

RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get install -y \
 apt-file \
 git-gui \
 git-svn \
#if DISTRO_trusty
# if !ARCH_arm64
 gnat \
# endif
#else
 gnat-5 \
#endif
 less \
 locales \
 mc \
 screen \
 stgit \
 tmux \
 && apt-get clean \
 && rm -rf \
 /var/lib/apt/lists/* \
 /tmp/* \
 /var/tmp/*

RUN locale-gen en_US.UTF-8 && update-locale LANG=en_US.UTF-8 \
 && apt-file update

# Create directories required for X11.
RUN mkdir -p /tmp/.X11-unix /tmp/.ICE-unix \
 && chmod 1777 /tmp/.X11-unix /tmp/.ICE-unix

COPY run.sh start.sh /

#if ARCH_amd64 || ARCH_arm64
ENTRYPOINT ["/run.sh"]
#else
ENTRYPOINT ["linux32", "/run.sh"]
#endif
CMD ["start.sh"]
