FROM linaro/ci-#{ARCH}-tcwg-base-ubuntu:#{DISTRO}

RUN apt-get update \
#if DISTRO_xenial
 && DEBIAN_FRONTEND=noninteractive apt-get install -y software-properties-common \
 && DEBIAN_FRONTEND=noninteractive add-apt-repository -y ppa:ubuntu-toolchain-r/test \
 && apt-get update \
#endif
 && DEBIAN_FRONTEND=noninteractive apt-get install -y \
 binutils-gold \
#if DISTRO_xenial
 buildbot \
 g++-9 \
#endif
 cpio \
 htop \
 iotop \
 libedit-dev \
 libjson-perl \
 libtinfo-dev \
 libxml2-dev \
 linux-tools-common \
#if DISTRO_xenial
 linux-tools-4.4.0-59-generic \
#elif DISTRO_focal
#linux-tools-NEED_TO_TEST \
#endif
#if DISTRO_xenial
 python-sphinx \
#endif
 swig \
 tmux \
 && apt-get clean \
 && rm -rf \
 /var/lib/apt/lists/* \
 /tmp/* \
 /var/tmp/*

RUN new-user.sh --user tcwg-buildslave

# Add current clang for libcxx bots.
RUN \
#if ARCH_arm64
 clang_ver=clang+llvm-6.0.0-aarch64-linux-gnu \
#else /* ARCH_armhf */
 clang_ver=clang+llvm-6.0.0-armv7a-linux-gnueabihf \
#endif
 && cd /usr/local \
 && wget --progress=dot:giga http://releases.llvm.org/6.0.0/$clang_ver.tar.xz \
 && tar xf $clang_ver.tar.xz \
 && rm $clang_ver.tar.xz
#if !DISTRO_xenial
# Install xenial's verion of buildbot
RUN \
 curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && \
 python2 ./get-pip.py && \
 pip2 install buildbot==0.8.12
#endif

VOLUME /home

COPY run.sh .
COPY start.sh .

#if ARCH_amd64 || ARCH_arm64
ENTRYPOINT ["/run.sh"]
#else
ENTRYPOINT ["linux32", "/run.sh"]
#endif
CMD ["start.sh"]
